version: '3'
services:
  db:
    container_name: belot_db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  node:
    container_name: belot
    build: .
    ports:
      - 80:8080
    tty: true
    links:
        - db
    environment:
      - MYSQL_URI=mysql://root:password@database_development:3306/belot
      - PORT=8080
